# docker-compose.yml

version: '3.8'
services:
  server:
      build:
        context: .
      command: npm run start:dev
      container_name: api_service      
      environment:
        - PORT=8080
      ports:
        - '8080:8080'
      volumes:
        - './src:/app/src'            
        - './nest-cli.json:/app/nest-cli.json'            
        - './tsconfig.json:/app/tsconfig.json'      
      depends_on:
        - postgres 


  postgres:
    image: postgres:13.5
    restart: always
    container_name: 'api_service_db'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: