FROM node:12

WORKDIR /app

# Copy files we need
COPY src /app/src
COPY package-lock /app
COPY package.json /app
COPY nodemon.json /app
COPY tsconfig.json /app
COPY nest-cli.json /app


# Install our package
RUN npm 



